-- Table: public.STANDARD_ELEMENTS

-- DROP TABLE IF EXISTS public."STANDARD_ELEMENTS";

CREATE TABLE IF NOT EXISTS public."STANDARD_ELEMENTS"
(
    "STDE_UUID" uuid NOT NULL,
    "STDE_NAME" text COLLATE pg_catalog."default" NOT NULL,
    "STDE_DEFINITION" json NOT NULL,
    CONSTRAINT "STANDARD_ELEMENTS_pkey" PRIMARY KEY ("STDE_UUID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."STANDARD_ELEMENTS"
    OWNER to postgres;

COMMENT ON TABLE public."STANDARD_ELEMENTS"
    IS 'Stores definitions for all standard elements.';